project_name: praelatus
release:
  github:
    owner: praelatus
    name: praelatus
builds:
- goos:
  - windows
  - linux
  - darwin
  goarch:
  - amd64
  goarm:
  - "6"
  main: praelatus.go
  flags: -tags release
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: praelatus
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  files:
  - LICENSE
  - README.md
  - build/client*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
